---
# Kafka Overwatch

services:
  kafka-overwatch:
    image: public.ecr.aws/compose-x/kafka-overwatch:${IMAGE_TAG:-latest}
    x-docker_opts:
      InterpolateWithDigest: true
    build:
      context: .
    ports:
      - 8000:8000/tcp
