---
# Local testing Kafka configuration

clusters:
  nasa:
    cluster_config:
#      schema_registry: sc
      kafka:
        bootstrap.servers: kafka.gcn.nasa.gov:9092
        security.protocol: sasl_ssl
        sasl.mechanism: OAUTHBEARER
        sasl.oauthbearer.method: oidc
        sasl.oauthbearer.client.id: "{% raw %}{{resolve:secretsmanager:/kafka/nasa/oidc:SecretString:sasl.oauthbearer.client.id}}{% endraw %}"
        sasl.oauthbearer.client.secret: "{% raw %}{{resolve:secretsmanager:/kafka/nasa/oidc:SecretString:sasl.oauthbearer.client.secret}}{% endraw %}"
        sasl.oauthbearer.token.endpoint.url: https://auth.gcn.nasa.gov/oauth2/token
        sasl.oauthbearer.scope: gcn.nasa.gov/kafka-public-consumer
        client.id: kafka-overwatch-dev
        acks: all
        socket.keepalive.enable: true
    reporting_config:
      notification_channels:
        sns:
          - name: default-topic
      exports:
        S3:
          bucket_name: "{{ env_var('EXPORTS_BUCKET_NAME') }}"
          prefix_key: kafka-cluster-reports
      output_formats:
        pandas_dataframe:
          - csv
          - json
      evaluation_period_in_seconds: 300

notification_channels:
  sns:
    default-topic:
      topic_arn: arn:aws:sns:eu-west-1:373709687836:kafka-usage-report
